package dosktop

import (
	"github.com/supercom32/dosktop/internal/memory"
	"github.com/supercom32/dosktop/internal/recast"
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestUpdateButtonState(test *testing.T) {
	commonResource.isDebugEnabled = true
	layerAlias1 := "Layer1"
	layerAlias2 := "Layer2"
	layerWidth := 40
	layerHeight := 20
	buttonAlias1 := "Button1"
	buttonAlias2 := "Button2"
	styleEntry := memory.NewTuiStyleEntry()
	InitializeTerminal(layerWidth, layerHeight)
	AddLayer(layerAlias1, 0, 0, layerWidth, layerHeight, 1, "")
	AddLayer(layerAlias2, 3, 2, 30, 20, 2, layerAlias1)
	Layer(layerAlias1)
	Color(4, 6)
	FillLayer(layerAlias1, "a1a2a3a4a5")
	Layer(layerAlias2)
	Color(3, 11)
	FillLayer(layerAlias2, "b1b2b3b4b5")
	memory.AddButton(layerAlias2, buttonAlias1, "ButtonText", styleEntry, 2, 2, 20, 7)
	memory.AddButton(layerAlias2, buttonAlias2, "ButtonText", styleEntry, 2, 10, 20, 7)
	memory.MouseMemory.SetMouseStatus(10, 5, uint(1), "")
	UpdateDisplay() // Must be done first to update the shared display.
	updateButtonStates()
	obtainedValue := memory.ButtonMemory[layerAlias2][buttonAlias1].IsPressed
	expectedValue := true
	assert.Equalf(test, expectedValue, obtainedValue ,"The button pressed state was not detected as expected!")
	memory.MouseMemory.SetMouseStatus(10, 5, 0, "")
	updateButtonStates()
	obtainedValue = memory.ButtonMemory[layerAlias2][buttonAlias1].IsPressed
	expectedValue = false
	assert.Equalf(test, expectedValue, obtainedValue ,"The button pressed state was not detected as expected!")
	UpdateDisplay()
}

func TestGetButtonClickIdentifier(test *testing.T) {
	commonResource.isDebugEnabled = true
	layerAlias1 := "Layer1"
	layerAlias2 := "Layer2"
	layerWidth := 40
	layerHeight := 20
	buttonAlias1 := "Button1"
	buttonAlias2 := "Button2"
	styleEntry := memory.NewTuiStyleEntry()
	InitializeTerminal(layerWidth, layerHeight)
	AddLayer(layerAlias1, 0, 0, layerWidth, layerHeight, 1, "")
	AddLayer(layerAlias2, 3, 2, 30, 20, 2, layerAlias1)
	Layer(layerAlias1)
	Color(4, 6)
	FillLayer(layerAlias1, "a1a2a3a4a5")
	Layer(layerAlias2)
	Color(3, 11)
	FillLayer(layerAlias2, "b1b2b3b4b5")
	memory.AddButton(layerAlias2, buttonAlias1, "ButtonText", styleEntry, 2, 2, 20, 7)
	memory.AddButton(layerAlias2, buttonAlias2, "ButtonText", styleEntry, 2, 10, 20, 7)
	memory.ButtonMemory[layerAlias2][buttonAlias2].IsPressed = true
	UpdateDisplay()
	layerEntry := commonResource.screenLayer
	obtainedValue := layerEntry.GetBasicAnsiStringAsBase64()
	expectedValue := "G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTVhMWEyYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTVhMWEyYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjFiMmIzYjRiNWIxYjJiM2I0YjViMWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjFiMmIzYjRiNWIxYjJiM2I0YjViMWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjEbWzM4OzI7MjU1OzI1NTsyNTVtG1s0ODsyOzE5MjsxOTI7MTkybeKUjOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgBtbMzg7MjswOzA7MG3ilJAbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMRtbMzg7MjsyNTU7MjU1OzI1NW0bWzQ4OzI7MTkyOzE5MjsxOTJt4pSCG1szODsyOzA7MDswbSAgICAgICAgICAgICAgICAgIOKUghtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIxG1szODsyOzI1NTsyNTU7MjU1bRtbNDg7MjsxOTI7MTkyOzE5Mm3ilIIbWzM4OzI7MDswOzBtICAgICAgICAgICAgICAgICAg4pSCG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjEbWzM4OzI7MjU1OzI1NTsyNTVtG1s0ODsyOzE5MjsxOTI7MTkybeKUghtbMzg7MjswOzA7MG0gICAgQnV0dG9uVGV4dCAgICDilIIbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMRtbMzg7MjsyNTU7MjU1OzI1NW0bWzQ4OzI7MTkyOzE5MjsxOTJt4pSCG1szODsyOzA7MDswbSAgICAgICAgICAgICAgICAgIOKUghtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIxG1szODsyOzI1NTsyNTU7MjU1bRtbNDg7MjsxOTI7MTkyOzE5Mm3ilIIbWzM4OzI7MDswOzBtICAgICAgICAgICAgICAgICAg4pSCG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjEbWzM4OzI7MjU1OzI1NTsyNTVtG1s0ODsyOzE5MjsxOTI7MTkybeKUlBtbMzg7MjswOzA7MG3ilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilJgbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMWIyYjNiNGI1YjFiMmIzYjRiNWIxYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMRtbMzg7MjswOzA7MG0bWzQ4OzI7MTkyOzE5MjsxOTJt4pSM4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAG1szODsyOzI1NTsyNTU7MjU1beKUkBtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIxG1szODsyOzA7MDswbRtbNDg7MjsxOTI7MTkyOzE5Mm3ilIIgICAgICAgICAgICAgICAgICAbWzM4OzI7MjU1OzI1NTsyNTVt4pSCG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjEbWzM4OzI7MDswOzBtG1s0ODsyOzE5MjsxOTI7MTkybeKUgiAgICAgICAgICAgICAgICAgIBtbMzg7MjsyNTU7MjU1OzI1NW3ilIIbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMRtbMzg7MjswOzA7MG0bWzQ4OzI7MTkyOzE5MjsxOTJt4pSCICAgIEJ1dHRvblRleHQgICAgG1szODsyOzI1NTsyNTU7MjU1beKUghtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIxG1szODsyOzA7MDswbRtbNDg7MjsxOTI7MTkyOzE5Mm3ilIIgICAgICAgICAgICAgICAgICAbWzM4OzI7MjU1OzI1NTsyNTVt4pSCG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIyYjNiNGI1G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0yYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjEbWzM4OzI7MDswOzBtG1s0ODsyOzE5MjsxOTI7MTkybeKUgiAgICAgICAgICAgICAgICAgIBtbMzg7MjsyNTU7MjU1OzI1NW3ilIIbWzM4OzI7MTI4OzEyODswbRtbNDg7MjsyNTU7MjU1OzBtYjJiM2I0YjUbWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYRtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMRtbMzg7MjswOzA7MG0bWzQ4OzI7MTkyOzE5MjsxOTJt4pSUG1szODsyOzI1NTsyNTU7MjU1beKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUmBtbMzg7MjsxMjg7MTI4OzBtG1s0ODsyOzI1NTsyNTU7MG1iMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhG1szODsyOzEyODsxMjg7MG0bWzQ4OzI7MjU1OzI1NTswbWIxYjJiM2I0YjViMWIyYjNiNGI1YjFiMmIzYjRiNRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtCg=="
	assert.Equalf(test, expectedValue, obtainedValue ,"The updated screen does not match the master original!")

	obtainedLayerAlias, obtainedButtonAlias := getButtonClickIdentifier(10, 5)
	obtainedValue2 := recast.GetArrayOfInterfaces(obtainedLayerAlias, obtainedButtonAlias)
	expectedValue2 := recast.GetArrayOfInterfaces(layerAlias2, buttonAlias1)
	assert.Equalf(test, expectedValue2, obtainedValue2 ,"The layer and button alias obtained did not match what was expected!")

	obtainedLayerAlias, obtainedButtonAlias = getButtonClickIdentifier(10, 13)
	obtainedValue2 = recast.GetArrayOfInterfaces(obtainedLayerAlias, obtainedButtonAlias)
	expectedValue2 = recast.GetArrayOfInterfaces(layerAlias2, buttonAlias2)
	assert.Equalf(test, expectedValue2, obtainedValue2 ,"The layer and button alias obtained did not match what was expected!")
}
