name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Tests
      run: go test -v ./...
      
    - name: Get Test Coverage
      run: |
        go test -coverprofile=coverage.txt
        bash <(curl -s https://codecov.io/bash)

